# Script to create flipped version of NiMare outputs
module load afni

set -e

# Create output folder (if needed)
if [ ! -d /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI ]; then mkdir /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI; fi

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/neurosynth_dataset_LDA50_mask.nii -input "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/code/fc_introspection/resources/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz"

