# Script to create flipped version of NiMare outputs
module load afni

set -e

# Create output folder (if needed)
if [ ! -d /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI ]; then mkdir /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI; fi

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__10_language_semantic_word_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__10_language_semantic_word_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__10_language_semantic_word_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__10_language_semantic_word_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__10_language_semantic_word_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__11_adults_age_older_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__11_adults_age_older_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__11_adults_age_older_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__11_adults_age_older_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__11_adults_age_older_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__12_motion_mt_biological_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__12_motion_mt_biological_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__12_motion_mt_biological_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__12_motion_mt_biological_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__12_motion_mt_biological_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__13_memory_encoding_retrieval_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__13_memory_encoding_retrieval_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__13_memory_encoding_retrieval_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__13_memory_encoding_retrieval_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__13_memory_encoding_retrieval_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__14_motor_cortex_movement_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__14_motor_cortex_movement_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__14_motor_cortex_movement_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__14_motor_cortex_movement_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__14_motor_cortex_movement_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__15_number_model_reasoning_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__15_number_model_reasoning_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__15_number_model_reasoning_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__15_number_model_reasoning_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__15_number_model_reasoning_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__16_speech_auditory_temporal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__16_speech_auditory_temporal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__16_speech_auditory_temporal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__16_speech_auditory_temporal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__16_speech_auditory_temporal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__17_task_prefrontal_cortex_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__17_task_prefrontal_cortex_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__17_task_prefrontal_cortex_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__17_task_prefrontal_cortex_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__17_task_prefrontal_cortex_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__18_gaze_awareness_eyes_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__18_gaze_awareness_eyes_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__18_gaze_awareness_eyes_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__18_gaze_awareness_eyes_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__18_gaze_awareness_eyes_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__19_eye_functional_target_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__19_eye_functional_target_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__19_eye_functional_target_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__19_eye_functional_target_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__19_eye_functional_target_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__1_adhd_pd_task_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__1_adhd_pd_task_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__1_adhd_pd_task_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__1_adhd_pd_task_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__1_adhd_pd_task_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__20_cognitive_controls_disease_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__20_cognitive_controls_disease_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__20_cognitive_controls_disease_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__20_cognitive_controls_disease_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__20_cognitive_controls_disease_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__21_attention_task_wm_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__21_attention_task_wm_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__21_attention_task_wm_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__21_attention_task_wm_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__21_attention_task_wm_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__22_pitch_rate_musicians_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__22_pitch_rate_musicians_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__22_pitch_rate_musicians_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__22_pitch_rate_musicians_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__22_pitch_rate_musicians_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__23_emotional_amygdala_emotion_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__23_emotional_amygdala_emotion_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__23_emotional_amygdala_emotion_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__23_emotional_amygdala_emotion_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__23_emotional_amygdala_emotion_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__24_social_social-cognition_cognition_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__24_social_social-cognition_cognition_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__24_social_social-cognition_cognition_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__24_social_social-cognition_cognition_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__24_social_social-cognition_cognition_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__25_reward_striatum_ventral_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__25_reward_striatum_ventral_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__25_reward_striatum_ventral_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__25_reward_striatum_ventral_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__25_reward_striatum_ventral_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__26_visual_object_objects_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__26_visual_object_objects_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__26_visual_object_objects_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__26_visual_object_objects_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__26_visual_object_objects_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__27_connectivity_functional_network_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__27_connectivity_functional_network_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__27_connectivity_functional_network_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__27_connectivity_functional_network_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__27_connectivity_functional_network_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__28_action_parietal_cortex_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__28_action_parietal_cortex_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__28_action_parietal_cortex_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__28_action_parietal_cortex_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__28_action_parietal_cortex_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__29_fear_ptsd_threat_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__29_fear_ptsd_threat_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__29_fear_ptsd_threat_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__29_fear_ptsd_threat_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__29_fear_ptsd_threat_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__2_functional_hallucinations_deception_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__2_functional_hallucinations_deception_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__2_functional_hallucinations_deception_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__2_functional_hallucinations_deception_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__2_functional_hallucinations_deception_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__30_schizophrenia_matter_volume_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__30_schizophrenia_matter_volume_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__30_schizophrenia_matter_volume_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__30_schizophrenia_matter_volume_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__30_schizophrenia_matter_volume_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__31_face_faces_recognition_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__31_face_faces_recognition_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__31_face_faces_recognition_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__31_face_faces_recognition_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__31_face_faces_recognition_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__32_decision_making_decision-making_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__32_decision_making_decision-making_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__32_decision_making_decision-making_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__32_decision_making_decision-making_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__32_decision_making_decision-making_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__33_et_al_et-al_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__33_et_al_et-al_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__33_et_al_et-al_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__33_et_al_et-al_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__33_et_al_et-al_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__34_task_training_performance_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__34_task_training_performance_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__34_task_training_performance_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__34_task_training_performance_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__34_task_training_performance_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__35_response_inhibition_task_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__35_response_inhibition_task_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__35_response_inhibition_task_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__35_response_inhibition_task_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__35_response_inhibition_task_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__36_task_control_functional_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__36_task_control_functional_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__36_task_control_functional_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__36_task_control_functional_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__36_task_control_functional_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__37_alcohol_use_drug_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__37_alcohol_use_drug_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__37_alcohol_use_drug_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__37_alcohol_use_drug_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__37_alcohol_use_drug_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__38_cortex_abstract_prefrontal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__38_cortex_abstract_prefrontal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__38_cortex_abstract_prefrontal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__38_cortex_abstract_prefrontal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__38_cortex_abstract_prefrontal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__39_familiar_social_unfamiliar_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__39_familiar_social_unfamiliar_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__39_familiar_social_unfamiliar_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__39_familiar_social_unfamiliar_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__39_familiar_social_unfamiliar_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__3_bold_signal_level_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__3_bold_signal_level_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__3_bold_signal_level_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__3_bold_signal_level_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__3_bold_signal_level_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__40_pain_insula_cortex_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__40_pain_insula_cortex_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__40_pain_insula_cortex_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__40_pain_insula_cortex_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__40_pain_insula_cortex_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__41_task_rotation_mental_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__41_task_rotation_mental_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__41_task_rotation_mental_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__41_task_rotation_mental_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__41_task_rotation_mental_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__42_self_cortex_mpfc_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__42_self_cortex_mpfc_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__42_self_cortex_mpfc_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__42_self_cortex_mpfc_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__42_self_cortex_mpfc_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__43_effects_women_expressions_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__43_effects_women_expressions_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__43_effects_women_expressions_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__43_effects_women_expressions_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__43_effects_women_expressions_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__44_eeg_frequency_white_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__44_eeg_frequency_white_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__44_eeg_frequency_white_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__44_eeg_frequency_white_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__44_eeg_frequency_white_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__45_rule_cortex_events_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__45_rule_cortex_events_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__45_rule_cortex_events_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__45_rule_cortex_events_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__45_rule_cortex_events_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__46_conflict_control_acc_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__46_conflict_control_acc_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__46_conflict_control_acc_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__46_conflict_control_acc_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__46_conflict_control_acc_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__47_sleep_cortex_prefrontal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__47_sleep_cortex_prefrontal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__47_sleep_cortex_prefrontal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__47_sleep_cortex_prefrontal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__47_sleep_cortex_prefrontal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__48_music_musical_temporal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__48_music_musical_temporal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__48_music_musical_temporal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__48_music_musical_temporal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__48_music_musical_temporal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__49_visual_auditory_cortex_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__49_visual_auditory_cortex_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__49_visual_auditory_cortex_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__49_visual_auditory_cortex_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__49_visual_auditory_cortex_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__4_children_adolescents_age_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__4_children_adolescents_age_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__4_children_adolescents_age_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__4_children_adolescents_age_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__4_children_adolescents_age_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__50_basal_ganglia_basal-ganglia_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__50_basal_ganglia_basal-ganglia_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__50_basal_ganglia_basal-ganglia_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__50_basal_ganglia_basal-ganglia_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__50_basal_ganglia_basal-ganglia_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__5_functional_anterior_navigation_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__5_functional_anterior_navigation_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__5_functional_anterior_navigation_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__5_functional_anterior_navigation_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__5_functional_anterior_navigation_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__6_depression_mdd_treatment_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__6_depression_mdd_treatment_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__6_depression_mdd_treatment_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__6_depression_mdd_treatment_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__6_depression_mdd_treatment_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__7_pet_tomography_emission_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__7_pet_tomography_emission_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__7_pet_tomography_emission_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__7_pet_tomography_emission_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__7_pet_tomography_emission_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__8_learning_learned_sequence_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__8_learning_learned_sequence_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__8_learning_learned_sequence_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__8_learning_learned_sequence_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__8_learning_learned_sequence_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__9_gyrus_frontal_inferior_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50__9_gyrus_frontal_inferior_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__9_gyrus_frontal_inferior_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__9_gyrus_frontal_inferior_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50__9_gyrus_frontal_inferior_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__0_network_state_resting_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__10_food_taste_weight_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__11_learning_training_practice_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__12_women_men_sex_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__13_fear_threat_smokers_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__14_disease_ad_pd_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__15_task_performance_cognitive_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__16_response_inhibition_control_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__17_motor_cortex_hand_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__18_number_ips_numerical_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__19_action_actions_observation_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__1_anxiety_trait_personality_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__20_control_conflict_task_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__21_matter_volume_structural_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__22_method_group_approach_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__23_asd_autism_group_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__24_age_adults_older_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__25_spatial_body_human_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__26_emotional_amygdala_negative_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__27_disorder_adhd_group_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__28_social_empathy_moral_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__29_stress_ptsd_trauma_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__2_cerebellar_cerebellum_basal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__30_decision_making_risk_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__31_model_models_prediction_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__32_pain_somatosensory_stimulation_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__33_memory_retrieval_encoding_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__34_frequency_hz_ms_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__35_schizophrenia_risk_genetic_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__36_placebo_treatment_dopamine_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__37_language_reading_word_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__38_semantic_category_representations_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__39_stimulation_tms_bpd_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__3_cortex_anterior_cingulate_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__40_face_faces_facial_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__41_imagery_mental_events_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__42_visual_cortex_sensory_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__43_magnetic_mechanisms_human_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__44_eye_sleep_gaze_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__45_motion_perception_visual_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__46_hemisphere_language_stroke_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__47_attention_attentional_target_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__48_prefrontal_cortex_pfc_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__49_depression_mdd_state_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__4_stimulus_time_repetition_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__5_gyrus_frontal_inferior_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__6_auditory_speech_temporal_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__7_reward_feedback_striatum_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__8_mpfc_social_medial_z_desc-specificity.nii.gz"

3dLRflip -LR -overwrite -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz" "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-orig/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz"
3drefit -orient RPI -space MNI "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz"
3dresample -overwrite -master /data/SFIMJGC_Introspec/2023_fc_introspection/nimare/NiMare_Decoding_Mask_GMribbon_2023.nii.gz -input "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz" -prefix "/data/SFIMJGC_Introspec/2023_fc_introspection/nimare/LDA50/meta-analyses-RPI/LDA50_abstract_weight__9_memory_working_wm_z_desc-specificity.nii.gz"

